version: '3.4'

services:

  api:
    container_name: desafio-python-api
    hostname: 'desafio-python.com'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - network
    depends_on:
      - db
    restart: on-failure:2
    env_file:
      - .env
    command: bash -c "alembic upgrade head & python -m server"

  db:
    container_name: desafio-python-postgres
    hostname: 'desafio-python-postgres.com'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=desafio
    networks:
      - network

  redis:
    container_name: desafio-python-redis
    hostname: 'desafio-python-redis.com'
    networks:
      - network
    image: redis:alpine
    command: redis-server
    ports:
      - '6379:6379'

networks:
  network:
    driver: bridge
